### ISSUE TITLE
defaultHandler should support include and select options for getOne request

### ISSUE THREAD

**Issue by bradchoate** [codeledge/ra-data-simple-prisma#31]
I'd like to pass through the `include` object to identify relational properties to include, but there isn't a `getOne` options key for `defaultHandler`.

Also, the 'create' and 'update' method handlers should also support Prisma's `include` option, to allow propagating relational properties.

**Comment by bradchoate** [comment]
Ah, I see #32 already addresses this issue.

**Comment by ogroppo** [comment]
Hi @bradchoate, just published `ra-data-simple-prisma@1.1.0` please give it a go and see if it works for you. One thing, since in defaultHandler you cannot pass the `Prisma.whateverModelArgs` interface as a generic, you won't have the same nice autocomplete of `select` and `include` as you would by using `getOneHandler<Prisma...findUniqueArgs>`

**Comment by bradchoate** [comment]
Yes, thank you so much!
