### ISSUE TITLE
Prisma error when updating a mongo record.

### ISSUE THREAD

**Issue by codeninja** [codeledge/ra-data-simple-prisma#49]
![image](https://user-images.githubusercontent.com/14914/192083125-1fd44e8c-2244-46bd-876f-3569441ebe25.png)

I have this error on update which prevents me from updating the model. Prisma omits the ID on the update. 

(the published issue is mine to fix)

I believe the same "filter out non-schema args" treatment that is applied to the create method would do the trick here.

![image](https://user-images.githubusercontent.com/14914/192083215-7d4e2d7b-2d12-4655-9da3-3d27578d350a.png)

**Comment by mshd** [comment]
Yes, the ID shouldn't be passed on. Have you checked our demo code?
@ogroppo  what about the "filter out non-schema args" for update?

**Comment by ogroppo** [comment]
Hi, in an edit resource the `<TextInput source="id" />` should not be added, otherwise it will try to update :)

If you really want to have it on the UI, then you can pass to the `updateHandler` the options `{skipFields: {id: true}}`

In regard to `filter out non-schema args` that is for the filters I believe sending empty string instead of null (don't remember exactly under what conditions)

**Comment by codeninja** [comment]
@mshd Reviewing my code, I'm not displaying the ID on the form in any way but it's still being included in the post.

![image](https://user-images.githubusercontent.com/14914/192103919-e07e3534-2db8-427e-b071-09c8e06d086f.png)
![image](https://user-images.githubusercontent.com/14914/192103944-bab77b53-c7d8-46a6-b71a-f15a41cb0656.png)
![image](https://user-images.githubusercontent.com/14914/192103982-25171da4-8482-4b9a-b9fa-f2fe4ed3008b.png)
![image](https://user-images.githubusercontent.com/14914/192104001-f59215a0-1fd3-4c12-82b0-d8d2e7c528f3.png)
